### ISSUE TITLE
With many streams over a single channel, Publications report NOT_CONNECTED

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#194]
I have around 400 streams over a single channel.  Some of the streams work fine, but the publication for a number of them report NOT_CONNECTED when doing an offer.  The system works without issue when I have a channel per stream.

I've attached a couple of log files filtered down to one of the streams that is not working (streamId: -1523337006).  The `app.txt` is our application logs showing successful creation of the publication and subscription.  The `cnc-stat` is the relevant lines from the AeronStat output.  `media-driver-admin.txt` is all of the related messages from the media driver logs with 'aeron.event.log=admin`.

[app.txt](https://github.com/real-logic/Aeron/files/107594/app.txt)
[cnc-stat.txt](https://github.com/real-logic/Aeron/files/107593/cnc-stat.txt)
[media-driver-admin.txt](https://github.com/real-logic/Aeron/files/107592/media-driver-admin.txt)

**Comment by mikeb01** [comment]
I've attached the output of the media driver logs, when I use a channel per stream.  Interesting difference is that the non-working case seems to go through a cycle of:

Available Image -> Unavailable Image -> Remove Image -> Available Image...

```
[1836079.127465] CMD_OUT_AVAILABLE_IMAGE...
[1836089.834921] CMD_OUT_ON_UNAVAILABLE_IMAGE...
[1836089.843762] CMD_OUT_AVAILABLE_IMAGE...
[1836099.843195] REMOVE_IMAGE_CLEANUP...
[1836100.843985] CMD_OUT_ON_UNAVAILABLE_IMAGE...
[1836100.875779] CMD_OUT_AVAILABLE_IMAGE...
[1836110.860664] REMOVE_IMAGE_CLEANUP...
[1836111.860625] CMD_OUT_ON_UNAVAILABLE_IMAGE...
```

[media-driver-admin2.txt](https://github.com/real-logic/Aeron/files/107623/media-driver-admin2.txt)

**Comment by mjpt777** [comment]
The media-driver-admin.txt has the following suspicious line:
```
[1836955.275960] CMD_OUT_ON_UNAVAILABLE_IMAGE [73/73]: �ٳz�� W   aeron:udp?group=239.193.0.1:10000|interface=1 -1523337006 [7653]
```

**Comment by mjpt777** [comment]
That media-driver-admin.txt file also has a lot of other unprintable characters. Does the original file have this issue or is a GitHub posting thing?

**Comment by mjpt777** [comment]
I've pushed a change the deals with the corrupted log. @mikeb01 can you try again?

**Comment by tmontgomery** [comment]
One thing mentioned by @mjpt777 is flow control and loss in this type of scenario. Flow control is per streamId. But when sharing a channel, it is quite easy to overflow the network (congestion) or the receiver RCVBUF. When multiple channels are used, the buffer sizing works out. But when sharing, it could be too small and too much on a single stream. This is really the area of congestion control.

So, @mikeb01, a few questions:
- how fast does the app send? It it sends as fast as Aeron allows, this probably will cause loss
- what is the NAK stats in AeronStat? This might be a symptom

The thought here is that loss of SETUPs (which come on the data channel) might delay connecting for some time.

What happens if the rate of sending is lowered?

**Comment by mikeb01** [comment]
This happens during start up, so a number of heartbeat messages are sent (around 100/s).  I'll lower that and try again.  I'll also have a look at the depth of the OS receive buffers.

**Comment by mikeb01** [comment]
I've reduced the number of messages per second down to 10-20 per second.  These are mainly heartbeats, so very small (<30 bytes).  Still the same issue.  The Send-Q and Recv-Q values from netstat are 0.  I've attached a full capture of AeronStat and another grep of the media driver admin logs.

[aeron-stat.txt](https://github.com/real-logic/Aeron/files/108902/aeron-stat.txt)
[aeron-media-driver3.txt](https://github.com/real-logic/Aeron/files/108904/aeron-media-driver3.txt)

**Comment by mjpt777** [comment]
Is this with the event logger fixes?

**Comment by tmontgomery** [comment]
No NAKs sent. So, highly unlikely that the issue is loss related.

**Comment by tmontgomery** [comment]
There are a number of subscribers on each streamId it seems.

**Comment by tmontgomery** [comment]
Is the media driver log from the same run? Having trouble matching things up.

**Comment by tmontgomery** [comment]
Ah. Seems that the start of the log is missing until correlationId 80 or so

**Comment by tmontgomery** [comment]
I'm following in the log that some Images are being removed very quickly after being added. Not sure why.

**Comment by tmontgomery** [comment]
@mikeb01 have you changed any timeout settings?

**Comment by mikeb01** [comment]
I had attempted to increase the imageLivenessTimeout, but actually made is shorter.  I've removed the setting and I'm rerunning.  However, I was seeing the images being added and removed quickly before that too.

I'll post new logs.  Note that the media driver log was filtered by a specific streamId, which was one of the ones have issues.  I'll post the full log next time.

**Comment by tmontgomery** [comment]
I was able to reproduce the available/unavailable sequence with a custom app. And do have an explanation.

I think the Receiver and possibly the Sender thread is being starved out and causing the timeout on the Image before it can send an SM.

What I did:
- used a single app that had many publications and many subscriptions (400 in this case)
- used SHARED for threading model to exaggerate any starvation

This caused unavailable images to be seen while subs and pubs being created.

What I did to remove the unavailable images:
- moved to the `aeron-throughput.properties` for the MediaDriver so that it has multiple threads with aggressive idle strategies.

This was on MacOS, but I believe that starvation of the Receiver thread might be easier when all traffic goes through a single socket. Each datagram is a single `recv()` even if it is a single socket.

**Comment by tmontgomery** [comment]
As it takes a while to create all the logbuffers, etc. This puts more pressure on the threads as well. What I would suggest is to use a setup that uses DEDICATED threading model as well as up the image liveness timeout.

**Comment by mikeb01** [comment]
For a bit more background this is testing our whole app (all 40 services) on a fairly powerful workstation (28 logical cores, 64GB ram).  I've had to use a IdleStrategy that does a Thread.sleep(1) in order to reduce the CPU load.  Lots of threads (40) spinning on LockSupport.parkNanos() does result in high CPU usage (load average around 20).  I'v also reduced the termBufferLength to 64K otherwise it runs out of memory.

**Comment by tmontgomery** [comment]
@mikeb01 makes sense. And probably makes the situation easier to happen. The IdleStrategy for the Receiver is probably the more critical one. But the Sender also needs to get things out pretty regularly.

You might lower the load somewhat by adjusting the heartbeat interval.

Also, `SleepingIdleStrategy` is there for you as well.

**Comment by tmontgomery** [comment]
BTW, I believe that most of this is a startup artifact. The number of files, etc. is a non-trivial amount of load being generated. Once up and running, it should be better. So, one tactic might be to create Publications and Subscriptions slower.

**Comment by tmontgomery** [comment]
A pause between `addPublication` does wonders here. Just tried it out. The publication creates at least 1 logbuffer. And may trigger an Image if the same media driver is in use. Which is a second logbuffer. So, in my test, I added a 30 msec pause between `addPublication` and things worked with SHARED threading model. Once up, sending worked fine.

**Comment by mikeb01** [comment]
I've made the services start up sequentially and added a 30ms pause.  Still see the same issue, but on fewer topics.  Moving back to SHARED for threading mode to see if that reduces load on the system.

**Comment by tmontgomery** [comment]
SHARED may make it worse. Or at least it does for me.

**Comment by mikeb01** [comment]
I see the same problem with both.  Serialising and slowing start up has improved it, but now it takes >13 minuntes to start my system instead of ~3.5.

**Comment by tmontgomery** [comment]
The main bottleneck is actually the driver conductor thread, I think. What IdleStrategy is it using?

**Comment by mikeb01** [comment]
BackOff...

**Comment by tmontgomery** [comment]
Try changing it to NoOp instead. Or make it so that it spins more. When I use the properties below, even with a 30ms sleep between addPublications, it takes less than 10 seconds.

```
aeron.image.liveness.timeout=10000000000
aeron.conductor.idle.strategy=uk.co.real_logic.agrona.concurrent.NoOpIdleStrategy
agrona.disable.bounds.checks=true
```

**Comment by mikeb01** [comment]
That still isn't working for me.  I think the basic problem is that I'm CPU constrained.  Switching to NoOp pushes up the load average.  I'm still confused as to why it works fine when I put all of the topics on separate channels.

**Comment by tmontgomery** [comment]
My thought is that the Receiver thread is less busy and can multiplex better when with many lightly loaded sockets using Select than a single busy one that is resource constrained. Also, when using Selector, it is only calling recv() on those sockets that are ready instead of polling a single one all the time. So, less load on the Receiver thread.

**Comment by tmontgomery** [comment]
and it probably is better with the Backoff strategy on the Receiver thread than the polling one is

**Comment by mikeb01** [comment]
By receiver do you mean for polling subscriptions?

**Comment by tmontgomery** [comment]
No. The actual Receiver in the conductor that receives data from the sockets and places it in the logbuffers for the Subscribers.

**Comment by mikeb01** [comment]
I've currently go that one set to backoff, but the numbers are very small so it is probably just falling back to LockSupport.parkNanos().

**Comment by tmontgomery** [comment]
Making the Receiver thread more responsive might help keep things alive. The Sender thread needs to be sending heartbeats also, but with a longer image timeout, things are slightly more forgiving.

I think it is possible to find a good combo here that lets things get all up and running. And the same changes needed for the Sender, Receiver, and Conductor threads will probably also help the system itself have lower latency.

**Comment by mikeb01** [comment]
At this point I'm not really concerned about latency or performance in general.  I really need a low resource use configuration so that I can have a functional system on dev workstations and in CI.  I will have a significantly different configuration in production and performance testing environments where I'll have the processes spread across multiple machine and far less resource contention.

**Comment by tmontgomery** [comment]
What I would suggest then is:

- longer heartbeat timeout. Probably set via MediaDriver.Context
- longer image timeout, `aeron.image.liveness.timeout`
- more responsive IdleStrategy for Receiver
- DEDICATED threading model
- slight delay between addPublications (maybe a sleep(1) only)

Have you tried using 2 channels and splitting things between them instead of all 400 or 1?

**Comment by tmontgomery** [comment]
BTW, unless you need to log events, the logging should be off as the event reader is on the Conductor thread.

**Comment by tmontgomery** [comment]
With the properties file added with a90201cec9420ed54dbdc13510b49a23c091d87d and the property added with d969c827c1a57df8c5967e92ab668da7e4cc473e , this seems to be more stable. My test takes about 2 seconds to create all 400 pubs and subs and sends just fine.

**Comment by mjpt777** [comment]
@mikeb01 Can you retest with master?

**Comment by mikeb01** [comment]
Will do on Friday, have an afternoon allocated for Aeron time.

**Comment by mikeb01** [comment]
I done a fair amount of experimentation today and found that if I distribute the publications across 50 addresses our system works and with 49 it fails.  I've used logging on the media driver to capture all of the ADD_PUBLICATION and ADD_SUBSCRIPTION events and built a test with that set of connections (tests are attached).

The test creates all of the subscriptions and publications then does a quick set intersection to ensure that there are no publications that don't have a subscription (some of the publications are commented out to make sure this criteria is met).  A thread is spawned that consumes all of the messages from the subscriptions, while the main thread publishes 1 message a second to each of the publications and counts how many of those publications reject the message with a NOT_CONNECTED response.  I've attached 2 tests PubSubTest_49Addresses.java and PubSubTest_50Addresses.java.  The 49 address implementation shows that 6 of the 592 publications report NOT_CONNECTED and with the 50 addresses variant only 1 does[1].  The test expects a media driver to be already running.

[tests.zip](https://github.com/real-logic/Aeron/files/147566/tests.zip)

[1] Worth noting that while 50 addresses allows the particular smoke test to run on our system, it is still not 100%.  My test isn't exercising that topic(s) that would be broken.

**Comment by mikeb01** [comment]
I've traced this to a bug in BiInt2ObjectMap.  Here is a test case the replicates the issue:

    @Test
    public void shouldPutAndGet() throws Exception
    {
        map.put(721632679, 333118496, "a");
        assertThat(map.get(721632679, 333118496), is("a"));

        map.put(721632719, -659033725, "b");
        assertThat(map.get(721632719, -659033725), is("b"));

        map.put(721632767, -235401032, "c");
        assertThat(map.get(721632767, -235401032), is("c"));

        map.put(721632839, 1791470537, "d");
        assertThat(map.get(721632839, 1791470537), is("d"));

        map.put(721633069, -939458690, "e");
        assertThat(map.get(721633069, -939458690), is("e"));

        map.put(721633127, 1620485039, "f");
        assertThat(map.get(721633127, 1620485039), is("f"));

        map.put(721633163, -1503337805, "g");
        assertThat(map.get(721633163, -1503337805), is("g"));

        map.put(721633229, -2073657736, "h");
        assertThat(map.get(721633229, -2073657736), is("h"));

        map.put(721633255, -1278969172, "i");
        assertThat(map.get(721633255, -1278969172), is("i"));

        map.put(721633257, -1230662585, "j");
        assertThat(map.get(721633257, -1230662585), is("j"));

        map.put(721633319, -532637417, "k");
        assertThat(map.get(721633319, -532637417), is("k"));
    }

**Comment by tmontgomery** [comment]
The BiInt2ObjectMap is used for dispatching SMs and NAKs. So, it would be possible that if the map drops entries....

@RichardWarburton looks like the map may have an issue.

**Comment by tmontgomery** [comment]
My guess would be that the key isn't handling negative keyPartB correctly. Could be how the compoundKey is calculated.

**Comment by tmontgomery** [comment]
I've added a fix for compoundKey that seems to work. @mikeb01 feel free to retest. Seems to work for me.

**Comment by tmontgomery** [comment]
BTW, this clicks everything into place and explains a lot. The more demuxing (less channels), then more likely for there for be a collision in the map, etc. Also, if testing with positive streamIds, never would see this.

**Comment by mikeb01** [comment]
I'll pick it up on Monday.

**Comment by tmontgomery** [comment]
No worries. Have a great weekend!

**Comment by mikeb01** [comment]
Fix is all good, closing.
