### ISSUE TITLE
MediaDriver Unaligned 8-byte access in StatusMessageFlyweight

### ISSUE THREAD

**Issue by neekolashall** [real-logic/aeron#359]
I  have encountered a repeatable JVM crash issue when starting the MediaDriver on a solaris 10 / sparc9 box.  This appears to be due to an unaligned write in an UnsafeBuffer made by the StatusMessageFlyweight.  I have reproduced this with aeron 1.2.5 and 1.3.0.

To diagnose I ran with the -javaagent:agrona-agent-0.9.6.jar as per the wiki and it returns the following (on windows 7 x64 and solaris 10/sparc9):

```
WARNING: /var/tmp/aeron-someuser already exists.
TRANSFORM org.agrona.concurrent.UnsafeBuffer
TRANSFORM io.aeron.protocol.DataHeaderFlyweight
[GC (Allocation Failure)  65536K->5467K(251392K), 0.0627118 secs]
TRANSFORM io.aeron.protocol.HeaderFlyweight
TRANSFORM io.aeron.protocol.SetupFlyweight
TRANSFORM io.aeron.protocol.RttMeasurementFlyweight
TRANSFORM io.aeron.protocol.NakFlyweight
TRANSFORM io.aeron.protocol.StatusMessageFlyweight
Exception in thread "main" org.agrona.agent.BufferAlignmentException: Unaligned 8-byte access (Index=28, Buffer Alignment Offset=0)
        at org.agrona.agent.BufferAlignmentInterceptor$Verifier.verifyAlignment(BufferAlignmentInterceptor.java:35)
        at org.agrona.concurrent.UnsafeBuffer.putLong(UnsafeBuffer.java:344)
        at io.aeron.protocol.StatusMessageFlyweight.receiverId(StatusMessageFlyweight.java:179)
        at io.aeron.driver.media.ReceiveChannelEndpointThreadLocals.<init>(ReceiveChannelEndpointThreadLocals.java:70)
        at io.aeron.driver.MediaDriver$Context.concludeNullProperties(MediaDriver.java:724)
        at io.aeron.driver.MediaDriver$Context.conclude(MediaDriver.java:539)
        at io.aeron.driver.MediaDriver.<init>(MediaDriver.java:170)
        at io.aeron.driver.MediaDriver.launch(MediaDriver.java:285)
        at io.aeron.driver.MediaDriver.launch(MediaDriver.java:274)
        at io.aeron.driver.MediaDriver.main(MediaDriver.java:144)
```

Is this something that can be looked at and resolved in the flyweight?  

I appreciate this target platform is unusual but in this instance I have a requirement to deploy a new server to legacy kit running Solaris 10 sparc9 architecture for a transient period.  More generally should we consider sparc/solaris as a platform generically supported if run with a 1.8 JVM but not specifically verified?

**Comment by mjpt777** [comment]
Thanks. We have not done much testing on Sparc but it should work and this is one we missed. We'll look at how best address this and will check all the protocol codecs for alignment in case we might have missed others.

**Comment by mjpt777** [comment]
@neekolashall  I've committed a fix for this. Can you please build and test to see if it works for you?

**Comment by neekolashall** [comment]
@mjpt777 Thanks for the quick response.  I can verify that the fix to the StatusMessageFlyweight has stopped it causing a JVM crash.  I did however hit one further alignment issue when starting the MediaDriver in the CncFileDescriptor which also causes a JVM crash.  It looks like the CLIENT_LIVENESS_TIMEOUT_FIELD_OFFSET needs a 4 byte pad, but this would break the Cnc compatibility and would need to follow your version strategy I expect.  

```
TRANSFORM org.agrona.concurrent.UnsafeBuffer
TRANSFORM io.aeron.protocol.DataHeaderFlyweight
TRANSFORM io.aeron.protocol.HeaderFlyweight
TRANSFORM io.aeron.protocol.SetupFlyweight
TRANSFORM io.aeron.protocol.RttMeasurementFlyweight
TRANSFORM io.aeron.protocol.NakFlyweight
TRANSFORM io.aeron.protocol.StatusMessageFlyweight
Exception in thread "main" org.agrona.agent.BufferAlignmentException: Unaligned 8-byte access (Index=20, Buffer Alignment Offset=0)
        at org.agrona.agent.BufferAlignmentInterceptor$Verifier.verifyAlignment(BufferAlignmentInterceptor.java:35)
        at org.agrona.concurrent.UnsafeBuffer.putLong(UnsafeBuffer.java:370)
        at io.aeron.CncFileDescriptor.fillMetaData(CncFileDescriptor.java:159)
        at io.aeron.driver.MediaDriver$Context.conclude(MediaDriver.java:557)
        at io.aeron.driver.MediaDriver.<init>(MediaDriver.java:164)
        at io.aeron.driver.MediaDriver.launch(MediaDriver.java:274)
        at io.aeron.driver.MediaDriver.launch(MediaDriver.java:263)
        at io.aeron.driver.MediaDriver.main(MediaDriver.java:137)
```

I attempted a local patch just to see how far I could get and manged to start the MediaDriver start without ByteBuddy errors and errors reported by ErrorStat.  Unfortunately none of the client's can seem to connect to the media driver.  They get a timeout talking to the driver when creating a publication (I just ran the sample program io.aeron.samples.StreamingPublisher).  The same patch works without issue on Windows, so I wonder if I'm now encountering some other unique platform isue with Solaris/sparc.  I'm not sure what the next steps to debug would be, or if I'm starting to enter rabbit hole territory here.

```
Exception in thread "main" io.aeron.exceptions.DriverTimeoutException: No response from driver within timeout
        at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:478)
        at io.aeron.ClientConductor.addPublication(ClientConductor.java:187)
        at io.aeron.Aeron.addPublication(Aeron.java:197)
        at io.aeron.samples.StreamingPublisher.main(StreamingPublisher.java:79)
```

**Comment by mjpt777** [comment]
We are bumping the CnC version on the next release so this is a good time to address this. Can you try the latest build? I've just made another change.

**Comment by neekolashall** [comment]
Thanks again for the quire response time.  The media driver now operates without any alignment issues or crashes.  

I have a residual issue where the clients are still not able to talk to the media driver (embedded or run in a separate JVM).  After tracing system calls and pmap/pfiles the memory mapped files appear to be created without issue but the DriverProxy times out waiting for the response when creating a publication.  The MediaDriver doesn't see the publication message (or any messages) and I experience the DriverTimeoutException as above.  

At this point I'm looking at retreating and finding another strategy to share some Redhat x86_64 Kit.  I get the feeling there are a range of other platform issues unique to sparc waiting to be found.  I'm happy to simply accept and close this ticket as the alignment fixes are generally applicable and useful.

**Comment by mjpt777** [comment]
Please close this one and investigate the other issue. 

It may be helpful to use the logging media driver and set logging to all. Also worth using the `LogInspector` to view the created publications or images.

https://github.com/real-logic/Aeron/blob/master/aeron-samples/scripts/logging-media-driver

https://github.com/real-logic/Aeron/wiki/Monitoring-and-Debugging

**Comment by mjpt777** [comment]
@neekolashall I think I've tracked this to a big endian issue that will be fixed in the next release.  Please let us know if the a release after 1.10.4 works for you.

**Comment by neekolashall** [comment]
Thanks, I’ll give this a test tomorrow.  Out of interest what other big endian architecture did you resolve this for?

**Comment by neekolashall** [comment]
@mjpt777 I ran against a current snapshot (f53dab6195a1147dea720543cec92404172ff831) and encountered a jvm crash.  It seems that there are some new byte alignment issues that have crept into the codebase.  

`$ java -cp aeron-all-1.10.6-SNAPSHOT.jar io.aeron.driver.MediaDriver
WARNING: /var/tmp/aeron-adm_nh7 already exists.
INFO: Aeron CnC file exists: /var/tmp/aeron-adm_nh7/cnc.dat
INFO: Aeron toDriver consumer heartbeat is (ms): 38815
WARNING: Existing errors saved to: 2018-08-22-09-17-26-145+1000-error.log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0xffffffff7dd77d8c, pid=18330, tid=0x0000000000000046
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode solaris-sparc compressed oops)
# Problematic frame:
# V  [libjvm.so+0xd77d8c]  Unsafe_SetInt+0x168
#
# Core dump written. Default location: /tmp/aeron-dist/core or core.18330
#
# An error report file with more information is saved as:
# /tmp/aeron-dist/hs_err_pid18330.log
Compiled method (nm)   24553  543     n 0       sun.misc.Unsafe::putInt (native)
 total in heap  [0xffffffff6a54db10,0xffffffff6a54def0] = 992
 relocation     [0xffffffff6a54dc38,0xffffffff6a54dc58] = 32
 main code      [0xffffffff6a54dc60,0xffffffff6a54dee8] = 648
 metadata       [0xffffffff6a54dee8,0xffffffff6a54def0] = 8
#`

I ran with the media driver with the agrona-agent and it picked up a couple of violations running the BasicPublisher and BasicSubscriber.  There may be more that have been introduced over the past year.

`Subscribing to aeron:udp?endpoint=localhost:40123 on stream Id 10
Exception in thread "main" io.aeron.exceptions.RegistrationException: errorCodeValue=0 BufferAlignmentException : Unaligned 8-byte access (Index=26, Buffer Alignment Offset=2)
        at io.aeron.ClientConductor.onError(ClientConductor.java:169)
        at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:85)
        at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:120)
        at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:56)
        at io.aeron.ClientConductor.service(ClientConductor.java:716)
        at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:752)
        at io.aeron.ClientConductor.addSubscription(ClientConductor.java:469)
        at io.aeron.ClientConductor.addSubscription(ClientConductor.java:443)
        at io.aeron.Aeron.addSubscription(Aeron.java:269)
        at io.aeron.samples.BasicSubscriber.main(BasicSubscriber.java:71)`

`Publishing to aeron:udp?endpoint=localhost:40123 on stream Id 10
Exception in thread "main" io.aeron.exceptions.RegistrationException: errorCodeValue=0 BufferAlignmentException : Unaligned 8-byte access (Index=63, Buffer Alignment Offset=7)
        at io.aeron.ClientConductor.onError(ClientConductor.java:169)
        at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:85)
        at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:120)
        at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:56)
        at io.aeron.ClientConductor.service(ClientConductor.java:716)
        at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:752)
        at io.aeron.ClientConductor.addPublication(ClientConductor.java:387)
        at io.aeron.Aeron.addPublication(Aeron.java:241)
        at io.aeron.samples.BasicPublisher.main(BasicPublisher.java:65)`

This isn't a critical issue but next cnc update it may be worth resolving the alignment issues.

Cheers.

**Comment by tmontgomery** [comment]
@neekolashall do you happen to have the error logs from the media driver? Will be in the current directory.

**Comment by neekolashall** [comment]
Sure, here are the jvm crash logs for a few runs.

[hs_err_pid2241.log](https://github.com/real-logic/aeron/files/2308442/hs_err_pid2241.log)
[hs_err_pid2595.log](https://github.com/real-logic/aeron/files/2308443/hs_err_pid2595.log)
[hs_err_pid3391.log](https://github.com/real-logic/aeron/files/2308444/hs_err_pid3391.log)
[hs_err_pid18330.log](https://github.com/real-logic/aeron/files/2308445/hs_err_pid18330.log)

**Comment by tmontgomery** [comment]
Thanks! I see the same cause for those. The ImagesBufferReadyFlyweight is possibly misaligned on the `sourceIdentity` field length depending on filename length. 

That is one we kind of know about. @mjpt777 and I have discussed changes for this. In trying to keep compatible with SBE, this is an issue as SBE has no way to prevent misaligned varData length fields. Although, we do know the charset and can use the fact that the field can be padded with nulls. Sadly, it's not a general fix for SBE, but would be something to consider.

However, not sure why that one would fire on a BasicPublisher, though.

**Comment by mjpt777** [comment]
There is a change in the SBE 2.0 RC spec that allows for var data and repeating group headers to be aligned. We could take a similar approach and align the var data length fields. I can find two sources: `ImagesBufferReadyFlyweight`  and `CounterMessageFlyweight`.

**Comment by mjpt777** [comment]
It will happen on the basic-publisher when the new publication matches an existing subscription and it is filtering the broadcast events and the error happen in the driver.

**Comment by mjpt777** [comment]
@neekolashall Can you try the latest build?

**Comment by neekolashall** [comment]
@mjpt777 I'm happy to report the latest commit 277929dea1afcd4cb16c71aeaf6473f2df17635a seems to have resolved the issues.  I verified with the streaming performance test and the ping/pong latency test.  Hopefully this exercise has contributed some value to Aeron.  Very impressive turnaround.

I've attached the cpuinfo from kstat and the sample console notes with the notes/console results.
[cpu_info.txt](https://github.com/real-logic/aeron/files/2312524/cpu_info.txt)
[aeron_solaris_sparcv9.txt](https://github.com/real-logic/aeron/files/2312525/aeron_solaris_sparcv9.txt)


Environment:

> $ kstat -p cpu_info | head -17
cpu_info:0:cpu_info0:brand      SPARC64-VII+
cpu_info:0:cpu_info0:chip_id    1024
cpu_info:0:cpu_info0:class      misc
cpu_info:0:cpu_info0:clock_MHz  2660
cpu_info:0:cpu_info0:core_id    0
cpu_info:0:cpu_info0:cpu_fru    hc:///component=/MBU_B/CPUM0
cpu_info:0:cpu_info0:cpu_type   sparcv9
cpu_info:0:cpu_info0:crtime     242.0386337
cpu_info:0:cpu_info0:current_clock_Hz   2660000000
cpu_info:0:cpu_info0:device_ID  46456528453639
cpu_info:0:cpu_info0:fpu_type   sparcv9
cpu_info:0:cpu_info0:implementation     SPARC64-VII+ (portid 1024 impl 0x7 ver 0xc1 clock 2660 MHz)
cpu_info:0:cpu_info0:pg_id      1
cpu_info:0:cpu_info0:snaptime   1595164.635855
cpu_info:0:cpu_info0:state      on-line
cpu_info:0:cpu_info0:state_begin        1533392977
cpu_info:0:cpu_info0:supported_frequencies_Hz   2660000000
$ cat /etc/release
                   Oracle Solaris 10 1/13 s10s_u11wos_24a SPARC
  Copyright (c) 1983, 2013, Oracle and/or its affiliates. All rights reserved.
                            Assembled 17 January 2013
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Best run (with defaults and 1 million messages):

> 
Pinging 1000000 messages
Histogram of RTT latencies in microseconds.
       Value     Percentile TotalCount 1/(1-Percentile)

      16.911 0.000000000000          2           1.00
      34.207 0.100000000000     100562           1.11
      36.031 0.200000000000     202668           1.25
      38.111 0.300000000000     302730           1.43
      38.911 0.400000000000     408553           1.67
      40.031 0.500000000000     504301           2.00
      40.927 0.550000000000     556304           2.22
      41.311 0.600000000000     609705           2.50
      41.503 0.650000000000     652310           2.86
      41.727 0.700000000000     700421           3.33
      42.015 0.750000000000     771005           4.00
      42.111 0.775000000000     791981           4.44
      42.207 0.800000000000     810731           5.00
      42.303 0.825000000000     827546           5.71
      42.527 0.850000000000     854662           6.67
      42.815 0.875000000000     881392           8.00
      43.007 0.887500000000     892404           8.89
      43.327 0.900000000000     902229          10.00
      44.127 0.912500000000     912556          11.43
      45.503 0.925000000000     925167          13.33
      47.103 0.937500000000     938000          16.00
      48.319 0.943750000000     944047          17.78
      49.503 0.950000000000     950027          20.00
      52.223 0.956250000000     956276          22.86
      55.231 0.962500000000     962687          26.67
      57.823 0.968750000000     968817          32.00
      60.127 0.971875000000     971914          35.56
      64.511 0.975000000000     975024          40.00
      73.023 0.978125000000     978126          45.71
      84.159 0.981250000000     981256          53.33
      97.535 0.984375000000     984386          64.00
     104.511 0.985937500000     985943          71.11
     111.935 0.987500000000     987512          80.00
     119.551 0.989062500000     989081          91.43
     127.743 0.990625000000     990645         106.67
     135.807 0.992187500000     992197         128.00
     140.543 0.992968750000     992976         142.22
     145.407 0.993750000000     993766         160.00
     150.399 0.994531250000     994539         182.86
     156.415 0.995312500000     995329         213.33
     162.943 0.996093750000     996099         256.00
     167.039 0.996484375000     996490         284.44
     171.007 0.996875000000     996896         320.00
     175.615 0.997265625000     997270         365.71
     181.247 0.997656250000     997659         426.67
     187.135 0.998046875000     998051         512.00
     190.207 0.998242187500     998248         568.89
     194.175 0.998437500000     998441         640.00
     198.399 0.998632812500     998640         731.43
     203.903 0.998828125000     998834         853.33
     210.303 0.999023437500     999028        1024.00
     213.503 0.999121093750     999126        1137.78
     217.599 0.999218750000     999220        1280.00
     221.311 0.999316406250     999319        1462.86
     226.815 0.999414062500     999415        1706.67
     232.063 0.999511718750     999513        2048.00
     235.519 0.999560546875     999562        2275.56
     239.999 0.999609375000     999610        2560.00
     244.223 0.999658203125     999660        2925.71
     249.599 0.999707031250     999708        3413.33
     255.615 0.999755859375     999758        4096.00
     260.095 0.999780273438     999781        4551.11
     264.447 0.999804687500     999805        5120.00
     270.335 0.999829101563     999831        5851.43
     276.223 0.999853515625     999854        6826.67
     284.415 0.999877929688     999879        8192.00
     288.511 0.999890136719     999892        9102.22
     293.375 0.999902343750     999903       10240.00
     298.239 0.999914550781     999916       11702.86
     301.823 0.999926757813     999927       13653.33
     306.943 0.999938964844     999939       16384.00
     317.183 0.999945068359     999946       18204.44
     321.023 0.999951171875     999952       20480.00
     331.519 0.999957275391     999958       23405.71
     335.871 0.999963378906     999964       27306.67
     344.831 0.999969482422     999970       32768.00
     345.855 0.999972534180     999974       36408.89
     355.839 0.999975585938     999976       40960.00
     357.887 0.999978637695     999979       46811.43
     373.759 0.999981689453     999982       54613.33
     394.751 0.999984741211     999985       65536.00
     398.335 0.999986267090     999987       72817.78
     404.735 0.999987792969     999988       81920.00
     428.543 0.999989318848     999990       93622.86
     433.919 0.999990844727     999991      109226.67
     441.599 0.999992370605     999993      131072.00
     444.415 0.999993133545     999994      145635.56
     444.415 0.999993896484     999994      163840.00
     446.463 0.999994659424     999995      187245.71
     447.487 0.999995422363     999996      218453.33
     454.655 0.999996185303     999997      262144.00
     454.655 0.999996566772     999997      291271.11
     454.655 0.999996948242     999997      327680.00
     491.007 0.999997329712     999998      374491.43
     491.007 0.999997711182     999998      436906.67
     497.919 0.999998092651     999999      524288.00
     497.919 0.999998283386     999999      582542.22
     497.919 0.999998474121     999999      655360.00
     497.919 0.999998664856     999999      748982.86
     497.919 0.999998855591     999999      873813.33
     498.943 0.999999046326    1000000     1048576.00
     498.943 1.000000000000    1000000
 [Mean    =       41.639, StdDeviation   =       15.027]
 [Max     =      498.943, Total count    =      1000000]
 [Buckets =           24, SubBuckets     =         2048]

**Comment by mjpt777** [comment]
@neekolashall BTW are you using the C or Java Media Driver?
