### ISSUE TITLE
Always missing the first message on a UDP stream

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#435]
Hello,

Recently I had issues with connectivity between multiple machines so I ran the SimplePublisher and SimpleSubscriber to test out if my udp channel configuration was right. 

SimplePublisher and SimpleSubscriber were started from different boxes with media drivers running on both machines. I started SimpleSubscriber first, then SimplePublisher. I turned on debug log to make sure that I didn't encountered problems like passing in the wrong endpoint. However, when I kicked out the SimplePublisher, it always exited immediately without the 5s wait as being said in the sample code with the following message,

```
Publishing to aeron:udp?endpoint=<ip-address>:8156 on stream Id 10
 Offer failed because publisher is not connected to subscriber
Done sending
```

And I also tried to run them from the same machine with each connecting to different media drivers to make sure that there is no firewall issue, but this still happened.

Then I switched over to run BasicPublisher and BasicSubscriber, which will keep sending messages. I started BasicSubscriber before BasicPublisher as well for this test. And this time I was surprised that they worked fine. However, the first message from the publisher is not sent because "publisher is not connected to subscriber".

```
Publishing to aeron:udp?endpoint=localhost:40123 on stream Id 10
Offering 0/1000000 - Offer failed because publisher is not connected to subscriber
No active subscribers detected -> The subscriber is listening on the channel, why?
Offering 1/1000000 - yay!
Offering 2/1000000 - yay!
Offering 3/1000000 - yay!
Offering 4/1000000 - yay!
Offering 5/1000000 - yay!
Offering 6/1000000 - yay!
Offering 7/1000000 - yay!
Offering 8/1000000 - yay!
Offering 9/1000000 - yay!
Offering 10/1000000 - yay!
Offering 11/1000000 - yay!
Offering 12/1000000 - yay!
...
```

My understanding was that if the subscriber is listening on a stream before a publication connected, the publication should always be able to detect that active subscriber when it's initialized. And this seems to be true with IPC stream. I am wondering if it should also be true on UDP or I'm making a wrong assumption here?

Thank you!

**Comment by mjpt777** [comment]
Whenever a publisher or subscriber is attempting there is a race to set up the connection. To be sure a connection is in place you can call `isConnected()` on either a Publication or Subscription. The `SimplePublisher` example should have been updated some time ago when we changed publications so that it was not possible to offer until a connection is established. I've corrected the sample.

The `BasicPublisher` and `BasicSubscriber` are working correctly. Sometimes the first publication offer may succeed or not as it is racing with the connection being established. The example is simply attempting to offer and it is reporting that the connection is not yet established.

**Comment by bedding** [comment]
Thanks for the clarification. I didn't find isConnected in Subscription though. Is it guaranteed that the subscriber can receive the message when isConnected() is true and offer() has succeeded? Is it possible that the subscriber can still miss the message?

**Comment by bedding** [comment]
Hey, I am still seeing message lost with udp stream with your suggestions. I used isConnected() function to check connectivity before offering anything with publication. I also checked image count on the subscription and I am pretty sure that both media drivers recognized each other. 

To make sure the the stream is "open open", I sent a connection ack message to the stream before sending any real data. And the ack message can always be received. However, my real data got lost very frequently, although it's not happening every time. And in this case, the offer call was always successful with return value greater than 1.

What may go wrong?

**Comment by mjpt777** [comment]
If you do not have the `Subscription.isConnected()` method then this suggests you are on an older version. Upgrading would be a good start.

Have you looked at the Aeron counter stats? Look for NAKs, short sends, and if the connections are established. If it happens and you can grab dump of the counters then this would help a lot with debugging.
